export const ACCOUNTS_CLIENT = Symbol('ACCOUNTS_CLIENT')
export const AUTH_CLIENT = Symbol('AUTH_CLIENT')
export const ACTORS_CLIENT = Symbol('ACTORS_CLIENT')
export const EMAIL_CLIENT = Symbol('EMAIL_CLIENT')
export const GENRES_CLIENT = Symbol('GENRES_CLIENT')
export const MOVIES_CLIENT = Symbol('MOVIES_CLIENT')
export const TOKENS_CLIENT = Symbol('TOKENS_CLIENT')
export const USERS_CLIENT = Symbol('USERS_CLIENT')
export const JWT_TOKENS_CLIENT = Symbol('JWT_TOKENS_CLIENT')
export const MEDIA_CLIENT = Symbol('MEDIA_CLIENT')

